#!/bin/bash
# ipad
# not an apple product

ip -o ad | awk '$2 != "lo" && $3 == "inet" {print $2, $4}'
ip -o route | awk '$1 == "default" {print $1, $3, $5}'

# sample output

#    $ ipad
#    enp5s0 192.168.1.101/24
#    default 192.168.1.1 enp5s0
